units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # M2 Screw Inserts
  screwRadius: 1.5
  standoffThickness: 3
  standoffDepth: 2.4
  # Case
  pcbThickness: 1.6
  baseThickness: 5.6
  wallThickness: 3
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      rotate: -30
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 15
            col_net: D11
            mirror.col_net: D11
        ring:
          key:
            stagger: 8
            spread: 23
            splay: -10
            col_net: D12
            mirror.col_net: D12
        middle:
          key:
            stagger: 5
            spread: 21
            splay: -5
            col_net: D13
            mirror.col_net: D13
        index:
          key:
            stagger: -8
            spread: 23
            splay: -5
            col_net: D14
            mirror.col_net: D14
      rows:
        bottom:
          row_net: D1
          mirror.row_net: D3
        top:
          row_net: D0
          mirror.row_net: D2
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
        row_net: D6
        mirror.row_net: D6
      anchor:
        ref: matrix_index_bottom
        shift: [14, 0]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: 3
            rotate: 90
            col_net: D11
            mirror.col_net: D13
        outer:
          key:
            width: 1.5kx
            rotate: 90
            col_net: D12
            mirror.col_net: D14
      rows:
        cluster:
          shift: [0, -2ky]
  mirror: &mirror
    ref: matrix_index_top
    distance: 2.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [-0.6px,-0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [1.26px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref:
            aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [0,-40]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: thumbs_inner_cluster
          shift: [1.26px,0.5py]
        - ref: matrix_index_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_ring_bottom
          shift: [-0.6px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  xlBoard:
    - what: outline
      name: board
      expand: wallThickness
  combo:
    - name: board
    - operation: subtract
      name: keys
  case:
    - name: xlBoard
    - operation: subtract
      name: board
    - operation: add
      name: keys
  mounting:
    holeTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_pinky_top]
        shift: [0.5px + 1.5,0.5py + 3]
    holeTopRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_pinky_top]
        shift: [0.5px + 1.5,0.5py + 3]
    holeBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeBottomRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_middle_bottom]
        shift: [0,-0.5py - 3]
    holeMiddleTopLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [matrix_index_top]
        shift: [-0.5px - 1, 10]
    holeMiddleTopRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_matrix_index_top]
        shift: [-0.5px - 1, 10]
    holeMiddleBottomLeft:
      radius: screwRadius
      what: circle
      where:
        ref: [thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
    holeMiddleBottomRight:
      radius: screwRadius
      what: circle
      where:
        ref: [mirror_thumbs_outer_cluster]
        shift: [-0.5kx - 3, 0.5kx]
  standoff:
    - what: outline
      name: mounting
      expand: standoffThickness
  battery_pocket:
    - what: rectangle
      size: [60, 25]
      where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0,-28]
  mcu_pocket:
    - what: rectangle
      size: [20, 24]
      where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0,-4]
pcbs:
  chouchou:
    template: kicad8
    outlines:
      main:
        outline:
          board
    footprints:
      choc:
        what: ceoloide/switch_choc_v1_v2
        where: -/thumbs_*/
        adjust:
          rotate: 0
        params:
          solder: true
          hotswap: true
          include_keycap: true
          keycap_width: kx-1
          keycap_height: ky-1
          include_corner_marks: true
          from:  "{{col_net}}"
          to: "{{colrow}}"
      choc_thumb:
        what: ceoloide/switch_choc_v1_v2
        where: /thumbs_*/
        adjust:
          rotate: 0
        params:
          solder: true
          hotswap: true
          include_keycap: true
          keycap_width: kx*1.5-1
          keycap_height: ky-1
          include_corner_marks: true
          from:  "{{col_net}}"
          to: "{{colrow}}"
      diode_main:
          what: ceoloide/diode_tht_sod123
          where: -/mirror_*/
          params:
            from: "{{colrow}}"
            to: "{{row_net}}"
            side: B
          adjust:
            shift: [5, -2]
            rotate: 180
      diode_mirror:
          what: ceoloide/diode_tht_sod123
          where: /mirror_*/
          params:
            from: "{{colrow}}"
            to: "{{row_net}}"
            side: B
          adjust:
            shift: [-5, -2]
            rotate: 0
      mcu:
        what: XIAO-nRF52840-Plus-SMD-Cutout
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [0,-8.5]
        params:
          side: B
          VCC3: VCC
          BATp: BAT_P
          flipx: true
      display:
          what: ceoloide/display_nice_view
          params:
            MOSI: D10
            SCK: D8
            CS: D7
          where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [0,-16]
      reset:
        what: ceoloide/reset_switch_tht_top
        where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [0,-40]
      battery_jst:
        what: ceoloide/battery_connector_jst_ph_2
        where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [0,-21.5]
            rotate: 0
        params:
          side: B
      holeTopLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_pinky_top]
          shift: [0.5px + 1.5,0.5py + 3]
      holeTopRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [mirror_matrix_pinky_top]
          shift: [0.5px + 1.5,0.5py + 3]
      holeBottomLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-0.5py - 3]
      holeBottomRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [mirror_matrix_middle_bottom]
          shift: [0,-0.5py - 3]
      holeMiddleTopLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [matrix_index_top]
          shift: [-0.5px - 1, 10]
      holeMiddleTopRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [mirror_matrix_index_top]
          shift: [-0.5px - 1, 10]
      holeMiddleBottomLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [thumbs_outer_cluster]
          shift: [-0.5kx - 3, 0.5kx]
      holeMiddleBottomRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [mirror_thumbs_outer_cluster]
          shift: [-0.5kx - 3, 0.5kx]
      creditText:
        what: ceoloide/utility_text
        where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [-22,-33]
        params:
          side: B
          text: ChouChou Flight\n---------------------\nOriginal Design\ngithub.com/dlip (Dane Lipscombe)\n---------------------\nFlight Edition Modifications\ngithub.com/lozengedrop (Zach Logan)
      ergogenlogo:
          what: ceoloide/utility_ergogen_logo
          where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [22,-30]
          params:
            side: B
      ergogentext:
        what: ceoloide/utility_text
        where:
            ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
            shift: [22,-36]
        params:
          text: Powered By\nErgogen
          side: B
cases:
  bottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: baseThickness + standoffDepth + pcbThickness
  _innerWall:
    - name: board
      extrude: baseThickness + standoffDepth + pcbThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: baseThickness + standoffDepth
  _standoffs:
    - name: standoff
      extrude: baseThickness + standoffDepth
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: bottom
      operation: add
    - what: case
      name: wall
      operation: add
    - name: battery_pocket
      operation: subtract
      extrude: 6
      shift: [0, 0, 2]
    - name: mcu_pocket
      operation: subtract
      extrude: 6
      shift: [0, 0, 2]
